import Member from '@/components/P-home/Member'
import Profile from '@/components/P-home/Profile'
import Title from '@/components/atoms/Title'
import { client } from 'libs/client'
import Head from 'next/head'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>DSL portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-32 m-auto w-4/5 sm:w-3/4 md:w-[66%] lg:w-3/5 flex flex-col justify-center items-center max-w-[40rem]">
        <Title title="Description" />
          <p>
            Welcome to DSL portfolio. This is a portfolio site for DSL members.
          </p>
        <Title title="Members" />
        <Profile data={data} />
        <Member data={data}/>
        <Title title="Products" />
        <Title title="Products" />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: 'portfolio',
    queries: {},
  })

  return {
    props: {
      data: data.contents,
    },
  }
}
